/* eslint-disable */
// Generated by Wrangler by running `wrangler types /Users/imjlk/repos/and-guide/webperf-selfhosted/apps/console/src/cloudflare-env.d.ts -c wrangler.jsonc --include-runtime false --strict-vars false` (hash: a4bbe8e0db30e7ba8f502dba3b10a8c2)
declare namespace Cloudflare {
	interface LocalEnv {
		CONTROL_BASE_URL: string;
		DEPLOY_TARGET: string;
		TURNSTILE_SITE_KEY: string;
	}
	interface Env {
		CONTROL_BASE_URL: string;
		DEPLOY_TARGET: string;
		TURNSTILE_SITE_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTROL_BASE_URL" | "DEPLOY_TARGET" | "TURNSTILE_SITE_KEY">> {}
}
