import { readFile, writeFile } from 'node:fs/promises';
import { relative, resolve } from 'node:path';

type Args = {
  cwd: string;
  output: string;
  configs: string[];
};

const parseArgs = (): Args => {
  const args = process.argv.slice(2);
  let cwd = process.cwd();
  let output = '';
  const configs: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    const next = args[index + 1];

    if (!next) {
      throw new Error(`Missing value for ${arg}`);
    }

    if (arg === '--cwd') {
      cwd = resolve(next);
      index += 1;
      continue;
    }

    if (arg === '--output') {
      output = next;
      index += 1;
      continue;
    }

    if (arg === '--config') {
      configs.push(next);
      index += 1;
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  if (!output) {
    throw new Error('--output is required');
  }

  if (configs.length === 0) {
    throw new Error('At least one --config is required');
  }

  return { cwd, output, configs };
};

const run = async () => {
  const { cwd, output, configs } = parseArgs();
  const outputPath = resolve(cwd, output);
  const original = await readFile(outputPath, 'utf8');

  const wranglerArgs = [
    'wrangler',
    'types',
    outputPath,
    ...configs.flatMap((config) => ['-c', config]),
    '--include-runtime',
    'false',
    '--strict-vars',
    'false'
  ];

  const result = Bun.spawn({
    cmd: ['bunx', ...wranglerArgs],
    cwd,
    stdout: 'pipe',
    stderr: 'pipe'
  });

  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(result.stdout).text(),
    new Response(result.stderr).text(),
    result.exited
  ]);

  try {
    process.stdout.write(stdout);
    process.stderr.write(stderr);

    if (exitCode !== 0) {
      process.exit(exitCode);
    }

    const generated = await readFile(outputPath, 'utf8');

    const normalize = (value: string) =>
      value.replace(
        /^\/\/ Generated by Wrangler by running `wrangler types .*?` \(hash: ([a-f0-9]+)\)$/m,
        '// Generated by Wrangler by running `wrangler types <normalized>` (hash: $1)'
      );

    if (normalize(original) !== normalize(generated)) {
      await writeFile(outputPath, original);
      const relativeOutput = relative(cwd, outputPath) || output;
      console.error(`Types at ${relativeOutput} are out of date. Run the matching types:cf script to regenerate.`);
      process.exit(1);
    }
  } finally {
    const current = await readFile(outputPath, 'utf8').catch(() => null);
    if (current !== null && normalizeForFinally(current) !== normalizeForFinally(original)) {
      await writeFile(outputPath, original);
    }
  }
};

const normalizeForFinally = (value: string) =>
  value.replace(
    /^\/\/ Generated by Wrangler by running `wrangler types .*?` \(hash: ([a-f0-9]+)\)$/m,
    '// Generated by Wrangler by running `wrangler types <normalized>` (hash: $1)'
  );

await run();
