services:
  console:
    image: webperf:dev
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.webperf

  api:
    image: webperf:dev
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.webperf

  scheduler:
    image: webperf:dev
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.webperf

  executor:
    image: webperf:dev
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.webperf

  probe:
    image: webperf-probe:dev
    build:
      context: ../../apps/probe-rs
      dockerfile: Dockerfile

  browser-audit-lighthouse:
    image: webperf-browser-audit-lighthouse:dev
    build:
      context: ../..
      dockerfile: apps/browser-audit-lighthouse/Dockerfile

  api-debug:
    image: webperf:dev
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.webperf

  browser-audit-debug:
    image: webperf:dev
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.webperf
